name: Python CI
on:
  push:
    branches:
      - main

jobs:
  python-ci:
    
    runs-on: ubuntu-latest

    steps:

      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Generate Report
        run: |
          poetry run coverage run -m pytest -s tests/
          