name: Python CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run:
    
    runs-on: ubuntu-latest

    steps:

      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Generate Report
        run: |
          coverage report -m